version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Пробрасываем порт 8000
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
      - ./database.db:/app/database.db
