version: '3.8'

services:
  fastapi:
    image: asdfrewqha/shock-fastapi-backend:latest
    container_name: fastapi-container
    env_file:
      - /root/fastapi/.env
    restart: unless-stopped
    expose:
      - 8000

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi
    restart: unless-stopped
