[tool.isort]
profile = "black"
line_length = 100
known_first_party = [
    "fastapi_server",
    "models",
    "config",
    "dependencies"
]
force_sort_within_sections = true
combine_as_imports = true
lines_after_imports = 2
lines_between_types = 1
include_trailing_comma = true
multi_line_output = 3
