name: Build and Deploy via Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: asdfrewqha/shock-fastapi-backend:latest


      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker stop fastapi-container || true
            docker rm fastapi-container || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
            docker run -d \
              --name fastapi-container \
              --env-file ~/fastapi/.env \
              -p 8000:8000 \
              ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
