name: Build and Deploy via Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Telegram notification (start)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          AUTHOR: ${{ github.actor }}
        run: |
          MESSAGE=$(cat <<EOF
Deploy starting:
Repo: $REPO
Branch: $BRANCH
Author: $AUTHOR
EOF
          )
          for ID in $TELEGRAM_CHAT_IDS; do
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
              -d chat_id="$ID" \
              -d text="$MESSAGE"
          done

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shock-fastapi-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/shock-fastapi-backend:latest
          cache-to: type=inline

      - name: Copy docker-compose.yml and nginx.conf to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 2084
          source: docker-compose.yml,nginx.conf
          target: /root/fastapi/

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 2084
          script: |
            set -e
            cd /root/fastapi

            echo "Stopping and removing old container if exists..."
            docker container rm -f fastapi-container || true
            docker container rm -f nginx-container || true

            echo "Pulling latest image..."
            docker pull asdfrewqha/shock-fastapi-backend:latest

            echo "Starting containers..."
            docker compose up -d --build --remove-orphans

            echo "Deployment finished successfully."

      - name: Telegram notification (success)
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          AUTHOR: ${{ github.actor }}
        run: |
          MESSAGE=$(cat <<EOF
Deployment finished successfully:
Repo: $REPO
Branch: $BRANCH
Author: $AUTHOR
EOF
          )
          for ID in $TELEGRAM_CHAT_IDS; do
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
              -d chat_id="$ID" \
              -d text="$MESSAGE"
          done

      - name: Telegram notification (fail)
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          AUTHOR: ${{ github.actor }}
        run: |
          MESSAGE=$(cat <<EOF
Deployment failure:
Repo: $REPO
Branch: $BRANCH
Author: $AUTHOR
Check workflow logs.
EOF
          )
          for ID in $TELEGRAM_CHAT_IDS; do
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
              -d chat_id="$ID" \
              -d text="$MESSAGE"
          done
